name: pr_mobile_mdp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/