// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJgNa2ff1Ef9UWHm1-pEYq_y3P_jYiMQ',
    appId: '1:834612149330:web:f7ea809d59cdea21feb38b',
    messagingSenderId: '834612149330',
    projectId: 'mdp-reg-flutter',
    authDomain: 'mdp-reg-flutter.firebaseapp.com',
    storageBucket: 'mdp-reg-flutter.firebasestorage.app',
    measurementId: 'G-GP2Y4SP5BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLipDH6ElBp7z9g0uVZNz1h4MRU22wqJI',
    appId: '1:834612149330:android:6b2008d5f29b442cfeb38b',
    messagingSenderId: '834612149330',
    projectId: 'mdp-reg-flutter',
    storageBucket: 'mdp-reg-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEJgNa2ff1Ef9UWHm1-pEYq_y3P_jYiMQ',
    appId: '1:834612149330:web:ce8566588eb4c749feb38b',
    messagingSenderId: '834612149330',
    projectId: 'mdp-reg-flutter',
    authDomain: 'mdp-reg-flutter.firebaseapp.com',
    storageBucket: 'mdp-reg-flutter.firebasestorage.app',
    measurementId: 'G-674V4W41K6',
  );
}
